language: python
python:
    - "3.7-dev"
services:
  - postgresql

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "create database ahdatabase;" -U postgres
    - python manage.py makemigrations
    - python manage.py migrate
    
script:
    - coverage run --source='.' manage.py test
          
after_success:
    - coveralls
