language: python
python:
    - "3.7"
services:
  - postgresql

env:
  - DJANGO=2.1

install:
    - pip install -r requirements.txt

script:
    - python manage.py test
    - coverage run manage.py test 
    
after_success:
    - coveralls