# Generated by Django 2.1.2 on 2018-11-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='reportarticle',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to='articles.Article'),
        ),
        migrations.AddField(
            model_name='reportarticle',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='articles.Article'),
        ),
        migrations.AddField(
            model_name='rating',
            name='reader',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='articles.Comment'),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likearticle',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to='articles.Article'),
        ),
        migrations.AddField(
            model_name='likearticle',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to='articles.Article'),
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to='articles.Article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to='articles.Article'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='tag_list',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                 through='taggit.TaggedItem', to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
