# Generated by Django 2.1.2 on 2018-11-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181108_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='articles.Article')),
            ],
        ),
    ]
