# Generated by Django 2.1.2 on 2018-11-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_views_count'),
        ('articles', '0003_auto_20181113_1420'),
    ]

    operations = [
    ]
