# Generated by Django 2.1.2 on 2018-11-08 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reader',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
    ]
