# Generated by Django 2.1.2 on 2018-11-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_merge_20181113_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
